
-- =========================================================
-- ORACLE DBA PLAYGROUND SCRIPT (11g & 19c)
-- Generated for learning & practice
-- NOTE:
-- Lines starting with '!' are OS commands (run in shell)
-- Everything else runs in SQL*Plus or SQLcl
-- =========================================================


/* =========================================================
   SECTION 1: LOGGING INTO ORACLE (OS SHELL)
   ========================================================= */

! sqlplus / as sysdba
! sqlplus system@ORCL
! sqlplus app_user/password@//localhost:1521/ORCLPDB


/* =========================================================
   SECTION 2: CONNECTION CONTEXT
   ========================================================= */

SELECT user FROM dual;
SELECT name FROM v$database;
SELECT instance_name, status FROM v$instance;
SELECT version FROM v$instance;


/* =========================================================
   SECTION 3: CDB / PDB (19c)
   ========================================================= */

SHOW con_name;

-- List PDBs (19c)
SELECT con_id, name, open_mode FROM v$pdbs;

-- Switch container (19c)
-- ALTER SESSION SET CONTAINER = ORCLPDB;


/* =========================================================
   SECTION 4: USERS & SECURITY
   ========================================================= */

-- Create user
CREATE USER app_user IDENTIFIED BY StrongPassword123;

-- Grant basic access
GRANT CREATE SESSION TO app_user;

-- Grant object privileges
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO app_user;

-- Tablespace quota
ALTER USER app_user QUOTA UNLIMITED ON users;

-- View users
SELECT username, account_status FROM dba_users;

-- Drop user
-- DROP USER app_user CASCADE;


/* =========================================================
   SECTION 5: OBJECT DISCOVERY
   ========================================================= */

SELECT table_name FROM user_tables;
SELECT view_name FROM user_views;
SELECT index_name FROM user_indexes;
SELECT sequence_name FROM user_sequences;


/* =========================================================
   SECTION 6: STORAGE & TABLESPACES
   ========================================================= */

SELECT tablespace_name, status FROM dba_tablespaces;

SELECT
  tablespace_name,
  ROUND(SUM(bytes)/1024/1024) AS size_mb
FROM dba_data_files
GROUP BY tablespace_name;


/* =========================================================
   SECTION 7: PLAYGROUND DATA
   ========================================================= */

CREATE TABLE playground_users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR2(50),
  created_at DATE DEFAULT SYSDATE
);

INSERT INTO playground_users (username) VALUES ('alice');
INSERT INTO playground_users (username) VALUES ('bob');
INSERT INTO playground_users (username) VALUES ('charlie');

COMMIT;

SELECT * FROM playground_users;


/* =========================================================
   SECTION 8: SESSIONS & LOCKS
   ========================================================= */

SELECT sid, serial#, username, status FROM v$session WHERE username IS NOT NULL;

SELECT
  l.session_id,
  o.object_name,
  l.locked_mode
FROM v$locked_object l
JOIN dba_objects o ON l.object_id = o.object_id;


/* =========================================================
   SECTION 9: BACKUP (RMAN – OS SHELL)
   ========================================================= */

! rman target /

-- Full database backup
-- BACKUP DATABASE;

-- Backup with archivelogs
-- BACKUP DATABASE PLUS ARCHIVELOG;


/* =========================================================
   SECTION 10: RESTORE & RECOVERY (RMAN)
   ========================================================= */

-- RESTORE DATABASE;
-- RECOVER DATABASE;


/* =========================================================
   SECTION 11: PITR (Point In Time Recovery)
   ========================================================= */

-- SHUTDOWN IMMEDIATE;
-- STARTUP MOUNT;

-- RUN {
--   SET UNTIL TIME "TO_DATE('2026-01-14 14:30:00','YYYY-MM-DD HH24:MI:SS')";
--   RESTORE DATABASE;
--   RECOVER DATABASE;
-- }

-- ALTER DATABASE OPEN RESETLOGS;


/* =========================================================
   SECTION 12: HIGH AVAILABILITY
   ========================================================= */

-- Data Guard role
SELECT database_role FROM v$database;

-- Standby status
SELECT process, status FROM v$managed_standby;

-- RAC (if applicable)
SELECT instance_name FROM gv$instance;


/* =========================================================
   SECTION 13: ENCRYPTION (TDE)
   ========================================================= */

-- Enable wallet (run once)
-- ADMINISTER KEY MANAGEMENT CREATE KEYSTORE '/u01/app/oracle/wallet' IDENTIFIED BY walletpwd;
-- ADMINISTER KEY MANAGEMENT SET KEY IDENTIFIED BY walletpwd WITH BACKUP;

-- Encrypt column
ALTER TABLE playground_users
MODIFY (username ENCRYPT);

-- Encrypt tablespace
-- CREATE TABLESPACE secure_ts DATAFILE 'secure01.dbf' SIZE 100M ENCRYPTION USING 'AES256' DEFAULT STORAGE(ENCRYPT);


/* =========================================================
   SECTION 14: MAINTENANCE
   ========================================================= */

EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'PLAYGROUND_USERS');


/* =========================================================
   SECTION 15: EXIT
   ========================================================= */

EXIT;
